# Generated by Django 4.0.4 on 2022-06-02 13:59

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.ImageField(upload_to=photos.models.get_file_path),
        ),
    ]
