# Generated by Django 4.0.4 on 2022-06-04 10:42

import django.core.validators
from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.ImageField(upload_to=photos.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Wrong file format!')]),
        ),
    ]
